version: '3'

services:
  tg-redirect:
    build: ./app
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - USE_PARSER=${USE_PARSER}
      - IMAGES_DIR=${IMAGES_DIR}
      - SITE_EMAIL=${SITE_EMAIL}
      - BLACKLIST=${BLACKLIST}
      - DEVELOPMENT=${DEVELOPMENT}
    image: tg-redirect
    hostname: tg-redirect
    container_name: tg-redirect
    restart: always
    volumes:
      - ./files/img:${IMAGES_DIR}
      - ./config:/config:ro
    ports:
      - 127.0.0.1:8000:8080
