version: '3'

services:
  tg-redirect:
    build: ./app
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MTPROXY_HOST=${MTPROXY_HOST}
      - MTPROXY_PORT=${MTPROXY_PORT}
      - MTPROXY_SECRET=${MTPROXY_SECRET}
      - SHOW_INFO=${SHOW_INFO}
    image: tg-redirect
    hostname: tg-redirect
    container_name: tg-redirect
    restart: always
    volumes:
      - ./files/img:/tmp/files/img
      - ./sessions:/tmp/sessions
    ports:
      - 127.0.0.1:8000:8080
